<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name'       => 'Tensimeter Digital Omron HEM-7120',
                'stock'      => 25,
                'price'      => 385000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2023-01-08 08:30:00',
                'updated_at' => '2023-01-08 08:30:00',
            ],
            [
                'name'       => 'Tensimeter Manual Riester',
                'stock'      => 15,
                'price'      => 275000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2023-02-14 09:15:00',
                'updated_at' => '2023-02-14 09:15:00',
            ],
            [
                'name'       => 'Stetoskop Littmann Classic III',
                'stock'      => 20,
                'price'      => 1250000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2023-03-21 10:45:00',
                'updated_at' => '2023-03-21 10:45:00',
            ],
            [
                'name'       => 'Stetoskop Onemed Dewasa',
                'stock'      => 30,
                'price'      => 85000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2023-04-05 11:20:00',
                'updated_at' => '2023-04-05 11:20:00',
            ],
            [
                'name'       => 'Termometer Digital Infrared',
                'stock'      => 40,
                'price'      => 175000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2023-05-17 13:10:00',
                'updated_at' => '2023-05-17 13:10:00',
            ],
            [
                'name'       => 'Termometer Raksa Oral',
                'stock'      => 50,
                'price'      => 25000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2023-06-29 14:00:00',
                'updated_at' => '2023-06-29 14:00:00',
            ],
            [
                'name'       => 'Pulse Oximeter Fingertip CMS50D',
                'stock'      => 35,
                'price'      => 145000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2024-01-10 08:40:00',
                'updated_at' => '2024-01-10 08:40:00',
            ],
            [
                'name'       => 'Glukometer Accu-Chek Active',
                'stock'      => 20,
                'price'      => 325000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2024-02-18 09:25:00',
                'updated_at' => '2024-02-18 09:25:00',
            ],
            [
                'name'       => 'Strip Gula Darah Accu-Chek (50 pcs)',
                'stock'      => 60,
                'price'      => 185000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2024-03-07 10:05:00',
                'updated_at' => '2024-03-07 10:05:00',
            ],
            [
                'name'       => 'Otoskop Diagnostik Heine Beta 200',
                'stock'      => 8,
                'price'      => 1850000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2024-04-22 11:55:00',
                'updated_at' => '2024-04-22 11:55:00',
            ],
            [
                'name'       => 'Reflex Hammer Babinski',
                'stock'      => 18,
                'price'      => 55000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2024-05-30 12:35:00',
                'updated_at' => '2024-05-30 12:35:00',
            ],
            [
                'name'       => 'Timbangan Badan Digital',
                'stock'      => 12,
                'price'      => 235000,
                'category'   => 'Alat Diagnostik',
                'image'      => null,
                'created_at' => '2024-06-11 14:45:00',
                'updated_at' => '2024-06-11 14:45:00',
            ],
            [
                'name'       => 'Nebulizer Omron NE-C28',
                'stock'      => 18,
                'price'      => 485000,
                'category'   => 'Alat Terapi',
                'image'      => null,
                'created_at' => '2025-01-09 08:10:00',
                'updated_at' => '2025-01-09 08:10:00',
            ],
            [
                'name'       => 'Nebulizer Mesh Portable',
                'stock'      => 22,
                'price'      => 350000,
                'category'   => 'Alat Terapi',
                'image'      => null,
                'created_at' => '2025-02-16 09:50:00',
                'updated_at' => '2025-02-16 09:50:00',
            ],
            [
                'name'       => 'TENS Terapi Nyeri Elektrik',
                'stock'      => 14,
                'price'      => 285000,
                'category'   => 'Alat Terapi',
                'image'      => null,
                'created_at' => '2025-03-25 10:30:00',
                'updated_at' => '2025-03-25 10:30:00',
            ],
            [
                'name'       => 'Infrared Lamp Terapi 150W',
                'stock'      => 10,
                'price'      => 195000,
                'category'   => 'Alat Terapi',
                'image'      => null,
                'created_at' => '2025-04-13 11:15:00',
                'updated_at' => '2025-04-13 11:15:00',
            ],
            [
                'name'       => 'Bantal Terapi Leher Cervical',
                'stock'      => 25,
                'price'      => 125000,
                'category'   => 'Alat Terapi',
                'image'      => null,
                'created_at' => '2025-05-28 13:25:00',
                'updated_at' => '2025-05-28 13:25:00',
            ],
            [
                'name'       => 'Korset Pinggang Lumbar Support',
                'stock'      => 30,
                'price'      => 175000,
                'category'   => 'Alat Terapi',
                'image'      => null,
                'created_at' => '2026-01-12 08:55:00',
                'updated_at' => '2026-01-12 08:55:00',
            ],
            [
                'name'       => 'Knee Brace Decker Lutut',
                'stock'      => 28,
                'price'      => 95000,
                'category'   => 'Alat Terapi',
                'image'      => null,
                'created_at' => '2026-02-20 09:35:00',
                'updated_at' => '2026-02-20 09:35:00',
            ],
            [
                'name'       => 'Ankle Brace Penyangga Pergelangan Kaki',
                'stock'      => 22,
                'price'      => 85000,
                'category'   => 'Alat Terapi',
                'image'      => null,
                'created_at' => '2026-03-18 10:20:00',
                'updated_at' => '2026-03-18 10:20:00',
            ],
        ];

        Product::insert($products);
    }
}